manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ShiniNet
      url-base: https://github.com/ShiniNet/
    - name: applepine1125
      url-base: https://github.com/applepine1125
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: kot149
      url-base: https://github.com/kot149
  projects:
    - name: zmk
      remote: applepine1125
      revision: a007c7b20fed45d2a39a5b1784dc6163f84f1d35  # v0.3.0 + PR #3483(スクロール解像度の宣言)。ブランチ lalapad-v0.3.0
      import: app/west.yml
    - name: zmk-driver-iqs9151
      remote: applepine1125
      revision: debd8c49bcfdb4a6d10be5e7955aadb63bb17c4e
    - name: zmk-easy-charge-indicator
      remote: ShiniNet
      revision: v1.0.0
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: v0.3
    - name: zmk-scroll-snap
      remote: kot149
      revision: v1
  self:
    path: config
